import "~/styles/globals.css";
import "cal-sans";

import { Inter } from "next/font/google";
import { ThemeProvider } from "~/components/theme-provider"

import { TRPCReactProvider } from "~/trpc/react";
import { Fog, GridContainer } from "~/components/madeup/grid-background";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <GridContainer> */}
          {/* <Fog /> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            forcedTheme="dark"
            disableTransitionOnChange
          >
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ThemeProvider>
        {/* </GridContainer> */}
      </body>
    </html>
  );
}
