import "~/styles/globals.css";
import "cal-sans";

import { Inter } from "next/font/google";
import { ThemeProvider } from "~/components/theme-provider";

import { TRPCReactProvider } from "~/trpc/react";
import { Fog, GridContainer } from "~/components/madeup/grid-background";
import { Cursor } from "~/components/madeup/cursor";
import { Toaster } from "~/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <GridContainer> */}
        {/* <Fog /> */}
        <Cursor />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          forcedTheme="dark"
          disableTransitionOnChange
        >
          <Toaster richColors={true} position="top-center" />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ThemeProvider>
        {/* </GridContainer> */}
      </body>
    </html>
  );
}
